server:
  port: 8003

spring:
  application:
    name: service-a

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka

  instance:
      prefer-ip-address: true

swagger:
  base-package: com.xaq