server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/geeknicker/springcloudConfig
          search-paths: respo
      label: master

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/

